#include "engine/brush/advanced_brushes.h"
#include <algorithm>
namespace creative::engine { namespace {void apply(TileStore&st,const BrushSample&p,double size,double opacity,auto fn){auto src=st.snapshot_rgba();int r=std::max(1,int(size/2));for(int y=-r;y<=r;++y)for(int x=-r;x<=r;++x){int px=std::clamp(int(p.x)+x,0,int(st.width()-1)),py=std::clamp(int(p.y)+y,0,int(st.height()-1));if(x*x+y*y>r*r)continue;auto i=(py*st.width()+px)*4;st.write_pixel(px,py,fn(src,i,st));}}}
void BlurBrush::stamp(TileStore&s,const BrushSample&p,double z,double o,std::uint32_t,BrushMode){apply(s,p,z,o,[](const auto&v,std::size_t i,const auto&st){int r=0;for(int k=0;k<4;++k)r+=std::to_integer<unsigned char>(v[i+k]);r/=4;return std::uint32_t(r)<<24|std::uint32_t(r)<<16|std::uint32_t(r)<<8|255;});}
void SmearBrush::stamp(TileStore&s,const BrushSample&p,double z,double o,std::uint32_t,BrushMode){apply(s,p,z,o,[&](const auto&v,std::size_t i,const auto&st){std::size_t q=std::min(v.size()-4,i+std::size_t(std::max(1,int(p.speed)))*4);return std::uint32_t(std::to_integer<unsigned char>(v[q]))<<24|std::uint32_t(std::to_integer<unsigned char>(v[q+1]))<<16|std::uint32_t(std::to_integer<unsigned char>(v[q+2]))<<8|255;});}
void CloneBrush::stamp(TileStore&s,const BrushSample&p,double z,double o,std::uint32_t,BrushMode){apply(s,p,z,o,[&](const auto&v,std::size_t i,const auto&st){std::size_t x=i/4%st.width(),y=i/4/st.width();std::size_t sx=std::clamp(int(x)+ox_,0,int(st.width()-1)),sy=std::clamp(int(y)+oy_,0,int(st.height()-1));auto q=(sy*st.width()+sx)*4;return std::uint32_t(std::to_integer<unsigned char>(v[q]))<<24|std::uint32_t(std::to_integer<unsigned char>(v[q+1]))<<16|std::uint32_t(std::to_integer<unsigned char>(v[q+2]))<<8|255;});}
void DodgeBrush::stamp(TileStore&s,const BrushSample&p,double z,double o,std::uint32_t,BrushMode){apply(s,p,z,o,[](const auto&v,std::size_t i,const auto&){auto c=[](int x){return std::min(255,x+32);};return std::uint32_t(c(std::to_integer<unsigned char>(v[i])))<<24|std::uint32_t(c(std::to_integer<unsigned char>(v[i+1])))<<16|std::uint32_t(c(std::to_integer<unsigned char>(v[i+2])))<<8|255;});}
void BurnBrush::stamp(TileStore&s,const BrushSample&p,double z,double o,std::uint32_t,BrushMode){apply(s,p,z,o,[](const auto&v,std::size_t i,const auto&){auto c=[](int x){return std::max(0,x-32);};return std::uint32_t(c(std::to_integer<unsigned char>(v[i])))<<24|std::uint32_t(c(std::to_integer<unsigned char>(v[i+1])))<<16|std::uint32_t(c(std::to_integer<unsigned char>(v[i+2])))<<8|255;});}
}
