#include "engine/brush/bitmap_brush.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <png.h>
namespace creative::engine {
bool BitmapBrush::load(const std::string& path){if(path.size()>4&&path.substr(path.size()-4)==".png"){FILE* fp=fopen(path.c_str(),"rb");if(!fp)return false;png_structp p=png_create_read_struct(PNG_LIBPNG_VER_STRING,nullptr,nullptr,nullptr);png_infop info=png_create_info_struct(p);if(!p||!info||setjmp(png_jmpbuf(p))){if(p)png_destroy_read_struct(&p,&info,nullptr);fclose(fp);return false;}png_init_io(p,fp);png_read_info(p,info);width_=png_get_image_width(p,info);height_=png_get_image_height(p,info);png_byte ct=png_get_color_type(p,info),bd=png_get_bit_depth(p,info);if(bd==16)png_set_strip_16(p);if(ct==PNG_COLOR_TYPE_PALETTE)png_set_palette_to_rgb(p);if(ct==PNG_COLOR_TYPE_GRAY&&bd<8)png_set_expand_gray_1_2_4_to_8(p);if(png_get_valid(p,info,PNG_INFO_tRNS))png_set_tRNS_to_alpha(p);if(ct==PNG_COLOR_TYPE_RGB||ct==PNG_COLOR_TYPE_GRAY||ct==PNG_COLOR_TYPE_PALETTE)png_set_filler(p,0xff,PNG_FILLER_AFTER);if(ct==PNG_COLOR_TYPE_GRAY||ct==PNG_COLOR_TYPE_GRAY_ALPHA)png_set_gray_to_rgb(p);png_read_update_info(p,info);pixels_.resize(width_*height_*4);std::vector<png_bytep> rows(height_);for(std::size_t y=0;y<height_;++y)rows[y]=reinterpret_cast<png_bytep>(pixels_.data()+y*width_*4);png_read_image(p,rows.data());png_destroy_read_struct(&p,&info,nullptr);fclose(fp);return true;}std::ifstream f(path,std::ios::binary);std::string magic;std::size_t max=0;if(!(f>>magic)||magic!="P6"||!(f>>width_>>height_>>max)||max!=255)return false;f.get();pixels_.resize(width_*height_*4);for(std::size_t i=0;i<width_*height_;++i){unsigned char rgb[3];if(!f.read(reinterpret_cast<char*>(rgb),3))return false;pixels_[4*i]=std::byte(rgb[0]);pixels_[4*i+1]=std::byte(rgb[1]);pixels_[4*i+2]=std::byte(rgb[2]);pixels_[4*i+3]=std::byte(255);}return true;}
void BitmapBrush::stamp(TileStore& store,const BrushSample& p,double size,double opacity,std::uint32_t,BrushMode){if(pixels_.empty())return;const int radius=std::max(1,int(std::lround(size/2)));const double angle=std::atan2(p.tilt_y,p.tilt_x),c=std::cos(angle),s=std::sin(angle);for(int y=-radius;y<=radius;++y)for(int x=-radius;x<=radius;++x){double sx=(x*c+y*s)/radius*.5+.5,sy=(-x*s+y*c)/radius*.5+.5;if(sx<0||sx>=1||sy<0||sy>=1)continue;std::size_t ix=std::min(width_-1,std::size_t(sx*width_)),iy=std::min(height_-1,std::size_t(sy*height_)),i=(iy*width_+ix)*4;if(std::to_integer<unsigned char>(pixels_[i+3])*opacity<128)continue;auto dx=std::clamp(long(std::lround(p.x+x)),0L,long(store.width()-1));auto dy=std::clamp(long(std::lround(p.y+y)),0L,long(store.height()-1));std::uint32_t color=std::uint32_t(std::to_integer<unsigned char>(pixels_[i]))<<24|std::uint32_t(std::to_integer<unsigned char>(pixels_[i+1]))<<16|std::uint32_t(std::to_integer<unsigned char>(pixels_[i+2]))<<8|std::uint32_t(std::to_integer<unsigned char>(pixels_[i+3]));store.write_pixel(std::size_t(dx),std::size_t(dy),color);}}
}
